

version: "3.8"

services:
  mongodb-user:
    image: mongo:6.0
    container_name: mongodb-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /host_mnt/c/Users/Sahar/WebstormProjects/DigitalWallet/mongo-data:/data/db
    networks:
      - digital_wallet_network

#   User Service
  user_service_server:
    container_name: user_service_server
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://root:root@mongodb-user:27017/userDb?authSource=admin
    depends_on:
      - mongodb-user
    volumes:
      - ./users:/usr/src/app
      - ./logs:/usr/src/app/logs
    networks:
      - digital_wallet_network


# Define a shared network for communication
networks:
  digital_wallet_network:
    driver: bridge
    external: true
