#services:
#  mongo:
#    image: mongodb/mongodb-community-server:latest
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/DigitalWallet/mongo-data:/data/db
#
#
#



#  users:
#    build:
#      context: ./users
#      dockerfile: Dockerfile
#    container_name: users-service
#    working_dir: /usr/src/app
#    ports:
#      - "3000:3000"
#    environment:
#      - PORT=3000
#      - MONGO_URI=mongodb://mongo:27017/digitalWallet
#    depends_on:
#      - mongo
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/DigitalWallet/users:/usr/src/app
#
#  notifications:
#    build:
#      context: ./notifications
#      dockerfile: Dockerfile
#    container_name: notifications-service
#    working_dir: /usr/src/app
#    ports:
#      - "3003:3003"
#    environment:
#      - PORT=3003
#      - MONGO_URI=mongodb://mongo:27017/digitalWallet
#    depends_on:
#      - mongo
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/DigitalWallet/notifications:/usr/src/app
#
#  transactions:
#    build:
#      context: ./transactions
#      dockerfile: Dockerfile
#    container_name: transactions-service
#    working_dir: /usr/src/app
#    ports:
#      - "3001:3001"
#    environment:
#      - PORT=3001
#      - MONGO_URI=mongodb://mongo:27017/digitalWallet
#    depends_on:
#      - mongo
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/transactions:/usr/src/app
#
#  groups:
#    build:
#      context: ./groups
#      dockerfile: Dockerfile
#    container_name: groups-service
#    working_dir: /usr/src/app
#    ports:
#      - "3002:3002"
#    environment:
#      - PORT=3002
#      - MONGO_URI=mongodb://mongo:27017/digitalWallet
#    depends_on:
#      - mongo
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/groups:/usr/src/app
#
#volumes:
#  mongo-data:
#

#    mongo:
#    image: mongodb/mongodb-community-server:latest
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - /Users/Sahar.Raz/WebstormProjects/DigitalWallet/mongo-data:/data/db

version: "3.8"

services:
  # MongoDB for Users
  mongodb-user:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /Users/Sahar.Raz/WebstormProjects/DigitalWallet/mongo-data:/data/db

#   User Service
  user_service_server:
    container_name: user_service_server
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://root:root@mongodb-user:27017/userDb
    depends_on:
      - mongodb-user
    volumes:
      - ./users:/usr/src/app


#  # MongoDB for Transactions
#  mongodb-transaction:
#    image: mongo:latest
#    container_name: mongodb-transaction
#    ports:
#      - "27018:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - ./transactionDb/db:/transactionDb/db
#
#  # MongoDB for Groups
#  mongodb-group:
#    image: mongo:latest
#    container_name: mongodb-group
#    ports:
#      - "27019:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - ./groupDb/db:/groupDb/db

#  # Transaction Service
#  transaction_service_server:
#    container_name: transaction_service_server
#    build:
#      context: ./transactions
#      dockerfile: Dockerfile
#    ports:
#      - "5002:5002"
#    environment:
#      PORT: 5002
#      MONGO_URI: mongodb://root:root@mongodb-transaction:27017/transactionDb
#    depends_on:
#      - mongodb-transaction
#    volumes:
#      - ./transactions:/usr/src/app
#
#  # Notification Service
#  notification_service_server:
#    container_name: notification_service_server
#    build:
#      context: ./notifications
#      dockerfile: Dockerfile
#    ports:
#      - "5003:5003"
#    environment:
#      PORT: 5003
#    volumes:
#      - ./notifications:/usr/src/app
#
#  # Group Service
#  group_service_server:
#    container_name: group_service_server
#    build:
#      context: ./groups
#      dockerfile: Dockerfile
#    ports:
#      - "5004:5004"
#    environment:
#      PORT: 5004
#      MONGO_URI: mongodb://root:root@mongodb-group:27017/groupDb
#    depends_on:
#      - mongodb-group
#    volumes:
#      - ./groups:/usr/src/app
